### PR TITLE
New package groff

### PR DESCRIPTION
**Pull request by PaperMountainStudio**
Should I use perl in deps of groff when groff requires texinfo that requires perl? But groff requires perl too.

### CODE REVIEW

**Comment by mitchweaver** [comment]
depends, is perl a runtime dep for groff? or a build time dep?

if its a build time dep, then it should only be on texinfo as it could be removed without a problem

but if its a run time dep, groff needs it too as it won't work without it

(this system is subject to change, but it's part of how the dep-deletion / orphan-detection function will work)

**Comment by PaperMountainStudio** [comment]
I removed perl and it seems to work. So I removed perl as dependency from groff.

**Comment by mitchweaver** [comment]
@PaperMountainStudio I have updated the `groff` pkgfile, see the extended commit comment for details

**Comment by mitchweaver** [comment]
Alright! Besides those points LGTM :+1:

**Comment by PaperMountainStudio** [comment]
Thanks, I will try not to make these mistakes next time. :)

**Comment by mitchweaver** [comment]
@PaperMountainStudio no worries! Thanks for contributing! :smile:

**Pull request merged**
