### PR TITLE
Bring upstream up to date

### PR DESCRIPTION
**Pull request by paper42**

### CODE REVIEW

**Comment by protonesso** [comment]
Also discord seems dead too

**Comment by PaperMountainStudio** [comment]
Part of this PR is also making IRC the main communication channel.

**Comment by protonesso** [comment]
Discord bridge?

**Comment by mitchweaver** [comment]
I had no idea this was still being pursued... I've been inactive for months!

**Comment by PaperMountainStudio** [comment]
No, Discord server was deleted from what I know.

**Comment by PaperMountainStudio** [comment]
I kind of use it, but not for the intended purpose. I use it for building static binaries for my old servers.

**Pull request merged**
